# Generated by Django 4.0.4 on 2022-04-24 13:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
                ('acceptance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('difficulty',
                 models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('question_html', models.TextField()),
                ('solution_html', models.TextField()),
                ('tags',
                 django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1023), default=list,
                                                           size=None)),
                ('companies',
                 django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1023), default=list,
                                                           size=None)),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'ordering': ['-acceptance', 'name'],
            },
        ),
    ]
