# Generated by Django 4.0.4 on 2022-04-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_link',
            field=models.URLField(blank=True, max_length=1023, null=True),
        ),
    ]
