# Generated by Django 4.0.4 on 2022-04-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_companies_alter_problem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='acceptance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
