DIFFICULTY_CHOICES = (
    ('easy', 'Easy'),
    ('medium', 'Medium'),
    ('hard', 'Hard'),
)

STATUS_CHOICES = (
    ('unread', 'Unread'),
    ('read', 'Read'),
    ('solved_easy', 'Solved Easily'),
    ('solved_medium', 'Solved Medium'),
    ('solved_hard', 'Solved Hard'),
    ('solved_tutorial', 'Solved Using Tutorial'),
)
COMPANIES = [
    'Google',
    'Adobe',
    'Aetion',
    'Affirm',
    'Airbnb',
    'Akuna Capital',
    'Alibaba',
    'Amazon',
    'AppDynamics',
    'Apple',
    'Baidu',
    'Bloomberg',
    'Citadel',
    'Cloudera',
    'Coupang',
    'Coursera',
    'Drawbridge',
    'Dropbox',
    'Epic Systems',
    'Expedia',
    'Facebook',
    'Fallible',
    'GE Digital',
    'Gilt Groupe',
    'GoDaddy',
    'Goldman Sachs',
    'Helix',
    'Houzz',
    'Hulu',
    'IXL',
    'Indeed',
    'Intuit',
    'LinkedIn',
    'LiveRamp',
    'Lyft',
    'MAQ Software',
    'Machine Zone',
    'Mathworks',
    'Microsoft',
    'NetEase',
    'Netsuite',
    'Palantir',
    'Pinterest',
    'Pocket Gems',
    'Poynt',
    'Pure Storage',
    'Quip',
    'Quora',
    'Rackspace',
    'Radius',
    'Riot Games',
    'Rubrik',
    'Samsung',
    'Snapchat',
    'Square',
    'Tencent',
    'TripleByte',
    'Twitter',
    'Two Sigma',
    'Uber',
    'Valve',
    'WAP',
    'Works Applications',
    'Yahoo',
    'Yatra',
    'Yelp',
    'Zappos',
    'Zenefits',
    'databricks',
    'eBay',
    'inmobi',
]
